version: '3.8'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    env_file:
      - ./hadoop-hive.env

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    env_file:
      - ./hadoop-hive.env

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9870,resourcemanager:8088
    env_file:
      - ./hadoop-hive.env

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop-hive.env

  spark-master:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-master
    restart: always
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - INIT_DAEMONS_FOR_SPARK=true
      - SERVICE_PRECONDITION=namenode:9870
    env_file:
      - ./hadoop-hive.env

  spark-worker-1:
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    container_name: spark-worker-1
    restart: always
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SERVICE_PRECONDITION=spark-master:7077
    env_file:
      - ./hadoop-hive.env

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    restart: always
    ports:
      - 10000:10000
    environment:
      - SERVICE_PRECONDITION=namenode:9870,hive-metastore:9083
    env_file:
      - ./hadoop-hive.env

  hive-metastore:
    image: bde2020/hive-metastore:2.3.2-postgresql-metastore
    container_name: hive-metastore
    restart: always
    ports:
      - 9083:9083
    env_file:
      - ./hadoop-hive.env

  postgresql:
    image: postgres:13
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  postgresql_data:


